export const meses=[
    {
        id:1,
        descricao:'Janeiro',
        mensalidade:[
            {
                id:1,
                jogadores:[
                    {
                        id:1,
                        nome:'lennon',
                        mensalidade:'PAGO'
                    },
                    {
                        id:2,
                        nome:'Bruno',
                        mensalidade:'PENDENTE'
                    }
                ]
            }
        ],
        placar:[
            {
                id:1,
                data:'12/01/19',
                quadro_2:
                {
                    colisao:8,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:3
                }, 
            },
            {
                id:2,
                data:'20/01/19',
                quadro_2:
                {
                    colisao:6,
                    adversario:2
                },
                quadro_1:
                {
                    colisao:5,
                    adversario:4
                }, 
            },
            {
                id:3,
                data:'27/01/19',
                quadro_2:
                {
                    colisao:5,
                    adversario:3
                },
                quadro_1:
                {
                    colisao:3,
                    adversario:8
                }, 
            },
            {
                id:4,
                data:'31/01/19',
                quadro_2:
                {
                    colisao:9,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:6
                }, 
            }
        ]
    },
    
    {
        id:2,
        descricao:'Fevereiro',
        placar:[
            {
                data:'12/01/19',
                quadro_2:
                {
                    colisao:8,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:3
                }, 
            },
            {
                data:'20/01/19',
                quadro_2:
                {
                    colisao:6,
                    adversario:2
                },
                quadro_1:
                {
                    colisao:5,
                    adversario:4
                }, 
            },
            {
                data:'27/01/19',
                quadro_2:
                {
                    colisao:5,
                    adversario:3
                },
                quadro_1:
                {
                    colisao:3,
                    adversario:8
                }, 
            },
            {
                data:'31/01/19',
                quadro_2:
                {
                    colisao:9,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:6
                }, 
            }
        ]
    },
    {
        id:3,
        descricao:'Março',
        placar:[
            {
                data:'12/01/19',
                quadro_2:
                {
                    colisao:8,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:3
                }, 
            },
            {
                data:'20/01/19',
                quadro_2:
                {
                    colisao:6,
                    adversario:2
                },
                quadro_1:
                {
                    colisao:5,
                    adversario:4
                }, 
            },
            {
                data:'27/01/19',
                quadro_2:
                {
                    colisao:5,
                    adversario:3
                },
                quadro_1:
                {
                    colisao:3,
                    adversario:8
                }, 
            },
            {
                data:'31/01/19',
                quadro_2:
                {
                    colisao:9,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:6
                }, 
            }
        ]},
    {
        id:4,
        descricao:'Abril',
        placar:[
            {
                data:'12/01/19',
                quadro_2:
                {
                    colisao:8,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:3
                }, 
            },
            {
                data:'20/01/19',
                quadro_2:
                {
                    colisao:6,
                    adversario:2
                },
                quadro_1:
                {
                    colisao:5,
                    adversario:4
                }, 
            },
            {
                data:'27/01/19',
                quadro_2:
                {
                    colisao:5,
                    adversario:3
                },
                quadro_1:
                {
                    colisao:3,
                    adversario:8
                }, 
            },
            {
                data:'31/01/19',
                quadro_2:
                {
                    colisao:9,
                    adversario:4
                },
                quadro_1:
                {
                    colisao:6,
                    adversario:6
                }, 
            }
        ]},
    {id:5,descricao:'Maio',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:6,descricao:'Junho',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:7,descricao:'Julho',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:8,descricao:'Agosto',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:9,descricao:'Setembro',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:10,descricao:'Outubro',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:11,descricao:'Novembro',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:6
            }, 
        }
    ]},
    {id:12,descricao:'Dezembro',placar:[
        {
            data:'12/01/19',
            quadro_2:
            {
                colisao:8,
                adversario:4
            },
            quadro_1:
            {
                colisao:6,
                adversario:3
            }, 
        },
        {
            data:'20/01/19',
            quadro_2:
            {
                colisao:6,
                adversario:2
            },
            quadro_1:
            {
                colisao:5,
                adversario:4
            }, 
        },
        {
            data:'27/01/19',
            quadro_2:
            {
                colisao:5,
                adversario:3
            },
            quadro_1:
            {
                colisao:3,
                adversario:8
            }, 
        },
        {
            data:'31/01/19',
            quadro_2:
            {
                colisao:9,
                adversario:4
            },
            quadro_1:
            {
                colisao:20,
                adversario:2
            }, 
        }
    ]},
];

export const bid=[
    {
        id:0,
        nome:'lennon',
        bid:'s'
    },{
        id:1,
        nome:'lennon',
        bid:'s'
    },{
        id:2,
        nome:'lennon',
        bid:'n'
    },{
        id:3,
        nome:'lennon',
        bid:'s'
    },{
        id:4,
        nome:'lennon',
        bid:'n'
    }
    ,{
        id:5,
        nome:'lennon',
        bid:'s'
    },{
        id:6,
        nome:'lennon',
        bid:'s'
    },{
        id:7,
        nome:'lennon',
        bid:'s'
    }
];
